---
subtitle: "Explorador de Variables"
format: dashboard
server: shiny
---

```{r lib_setup}
#| context: setup
library(plotly)
```

```{r CargaParam}
#| output: false
#| context: data
fs::path(bsm_path, "Scripts/Carga Parametros.R") |> source()
```


```{r Load_Model_Artifacts}
"Modelo.zip" |> 
  with_working_path() |> 
  unzip(exdir = with_working_path("."))
```

```{r IVs}
#| context: data
#| 
# Por ahora no: "Vars Candidatas en Desarrollo por Grupos" = "Estab_ivs_cand_InS_x_grupo.Rdat", 
estab_ivs_files <- list("Vars Candidatas en Desarrollo" = "Estab_ivs_cand_InS.Rdat",
                        "Vars Modelo en Desarrollo" = "Estab_ivs_mod_InS.Rdat",
                        "Vars Modelo en Nueva Muestra" = "Estab_ivs_mod_OoS.Rdat")

estab_ivs_files |> 
  map(with_working_path) |> 
  keep(fs::file_exists) -> estab_ivs_available

estab_ivs_available |> 
  pluck(1) |> 
  read_rds() -> df_estab_Part
```

```{r DetallesTablasCont}
#| context: data
df_estab_Part |> 
  pluck('xvars') |>  
#  filter(tipo == 'Continua') |> 
#  filter(variable %in% (vars_mod |> stringr::str_remove("_g$"))) |> 
  mutate(var_name = paste(variable, 'en', valor_grupo)) |> 
  rename(direction = sentido) |> 
  select(tipo, variable, valor_grupo, var_name, direction, iv_tab) -> res
error = (nrow(res)==0)
if (error) message("Ninguna variable continua integra el modelo! Detalle de tablas no generado!")
res |> pluck('variable') |> unique() -> variables
res |> pluck('valor_grupo') |> unique() -> grupos
```

#  {.sidebar width="250px"}

```{r Inputs}
selectInput("rep_iv", label = "Elija reporte", choices = names(estab_ivs_available))
br()
selectInput('variable', label = 'Variable', choices = variables)
br()
textOutput("var_tipo")
br()
selectInput('grupo', label = 'Grupo', choices = grupos)
br()
actionButton(inputId = "stop_app", label = "Terminar", icon = icon("sign-out-alt")) 
br()
br()
#textOutput("tiempo_restante")
```

# **`r project_title`**

```{r Outputs}
#| panel: fill
plotlyOutput('plot_iv')

gt_output("table_iv")
```

```{r Server}
#| context: server
#| message: false
#| warning: false

# SF, de https://stackoverflow.com/questions/77853364/stop-shiny-app-after-specific-amount-of-time-without-activity#:~:text=The%20Shiny%20invalidateLater%28%29%20function%20will%20help%20you%20accomplish,when%20the%20specified%20number%20of%20milliseconds%20has%20passed.
# choose number of milliseconds for how often to check idle time
checkInterval <-  60000 # Chequea cada 60 segundos 

# choose number of idle minutes that should trigger the modal dialog
maxIdleAsk <- 15 # La idea es que si responde que no, no llega a dispararse de nuevo la pregunta porque se alcanza maxIdleMins

# choose number of idle minutes that should trigger the app to close
maxIdleMins <- 16

# create reactive variable to track the number of minutes app has been idle
idle <- reactiveVal(0) 

# initialize the lastActivity reactive variable value to the current time
lastActivity <- reactiveVal(isolate(Sys.time()))

observeEvent({
  input$rep_iv
  input$variable
  input$grupo
  }, {
  lastActivity(isolate(Sys.time()))
})

observe({   
  # This reactive expression will re-evaluate after checkInterval milliseconds 
  # has passed due to invalidateLater function.
  invalidateLater(checkInterval)
  # number of minutes since last activity
  idle(difftime(isolate(Sys.time()), lastActivity(), units = "mins")) 

  if (idle() > maxIdleAsk) {
    show_timeout_warning()
  }
  
  if (idle() > maxIdleMins) {
    stopApp()
  }

})

output$tiempo_restante <- renderText({ maxIdleMins - idle() })

# Function to show the timeout warning modal
show_timeout_warning <- function() {
  showModal(modalDialog(
    title = "Aviso de Inactividad",
    "Su sesión va a expirar por inactividad. ¿Necesita más tiempo?",
    footer = tagList(
      modalButton("No"),
      actionButton("extend_time", "Sí, necesito más tiempo.")
    )
  ))
}
 
# Extend session upon user request
observeEvent(input$extend_time, {
  lastActivity(isolate(Sys.time()))
  removeModal()
})
  
df_estab <- reactive({
  req(input$rep_iv)
  estab_ivs_available[[input$rep_iv]] |> 
    read_rds() |> 
    pluck('xvars') |>  
    mutate(var_name = paste(variable, 'en', valor_grupo)) |> 
    rename(direction = sentido) |> 
    select(tipo, variable, valor_grupo, var_name, direction, iv_tab) -> res
  error = (nrow(res)==0)
  # browser() # Ojo que no anda aquí inline {input$rep_iv}
  if (error) 
    error_custom("x"="Error! Reporte de IVs de variables no encontrado!", 
             "i"="No se encontró!", input$rep_iv,  
             ">"=cli::col_red("Cod 600"))
  return(res)
})

observeEvent(df_estab(), {
  freezeReactiveValue(input, "variable")
  freezeReactiveValue(input, "grupo")
    
  df_estab() |> pluck('variable') |> unique() -> choices 
  updateSelectInput(inputId = "variable", choices = choices)
  
  df_estab() |> pluck('valor_grupo') |> unique() -> choices 
  updateSelectInput(inputId = "grupo", choices = choices)
})

selectedData <- reactive({
  req(input$variable)
  df_estab() |> 
    filter(variable == input$variable) 
})

var_type <- reactive({
  req(selectedData())
  selectedData() |> pluck('tipo', 1)  
})

output$var_tipo <- renderText({ var_type() })

output$plot_iv <- renderPlotly({
  req(selectedData())
  if (var_type()=='Continua') {
    selectedData() |> 
      iv_grouped_tab_cont_2_plotly()
  } else {
    selectedData() |> 
      iv_grouped_tab_categ_2_plotly()
  } 
})

output$table_iv <- render_gt({
  req(input$variable)
  req(input$grupo)
  req(selectedData())
    if (var_type()=='Continua') {
      selectedData() |> 
        filter(valor_grupo == input$grupo) |> 
        pluck('iv_tab', 1) |> 
        det_iv_cont_gt(title = paste(input$variable, "en", input$grupo))
    } else {
      selectedData() |> 
        filter(valor_grupo == input$grupo) |> 
        pluck('iv_tab', 1) |> 
        det_iv_categ_gt(title = paste(input$variable, "en", input$grupo))
    }
})

observeEvent(input$stop_app, { stopApp() })
```
