#
# ------------------------------------------------------------------------------
# Antes tenía agregado de servidor SSH desde sebastianf101/bsm-studio-paq:v2.2.1
# Refs: https://github.com/atmoz/sftp
#
# Define build-time arguments with default values
ARG BASE_IMAGE_REPO=bsm-studio-paq
ARG BASE_IMAGE_VERSION=latest
ARG REPO_SOURCE_URL

# Use the supplied base image name and version
# ghcr.io/sferro-besmart/my-rstudio:1.0.1
FROM ${BASE_IMAGE_REPO}:${BASE_IMAGE_VERSION} AS base

ARG BSM_VERSION=10.3
ENV BSM_VERSION=${BSM_VERSION}
ENV BSM_USER=user
ENV BSM_DIR=/home/${BSM_USER}/Documents/besmart/${BSM_VERSION}

# Apply metadata labels dynamically
#LABEL org.opencontainers.image.source=${REPO_SOURCE_URL}

# Build context is project root.
COPY ./docker/RProfile.site /usr/local/lib/R/etc/Rprofile.site
#
# Alta de usuarios
RUN addgroup --gid 1000 consultores_ext
COPY ./docker/users.conf.newusers /etc/security/users.conf.newusers
RUN chmod 0600 /etc/security/users.conf.newusers
RUN newusers /etc/security/users.conf.newusers
#
# Inicializa los directorios del usuario.
RUN mkdir -p "${BSM_DIR}"
COPY ./volume_versiones/${BSM_VERSION}/ "${BSM_DIR}/"
RUN mkdir -p "${BSM_DIR}/Logs" "${BSM_DIR}/Trabajo" "${BSM_DIR}/Reportes" "${BSM_DIR}/Auxil"
RUN chown -R ${BSM_USER}:consultores_ext "${BSM_DIR}"
# set up SSH
# Set up SSH for user 'user'# SSH config (pubkey only) with StrictModes
RUN mkdir -p /var/run/sshd && \
    sed -ri 's|^#?PasswordAuthentication.*|PasswordAuthentication no|' /etc/ssh/sshd_config && \
    sed -ri 's|^#?PermitRootLogin.*|PermitRootLogin no|' /etc/ssh/sshd_config && \
    sed -ri 's|^#?PubkeyAuthentication.*|PubkeyAuthentication yes|' /etc/ssh/sshd_config && \
    sed -ri 's|^#?AuthorizedKeysFile.*|AuthorizedKeysFile .ssh/authorized_keys|' /etc/ssh/sshd_config && \
    sed -ri 's|^#?StrictModes.*|StrictModes yes|' /etc/ssh/sshd_config && \
    echo 'PermitUserEnvironment yes' >> /etc/ssh/sshd_config

# ~/.ssh with strict perms for 'user'
RUN install -d -m 700 -o user -g consultores_ext /home/user/.ssh

# Add the public key as authorized_keys
COPY ./docker/id_rocker.pub /home/user/.ssh/authorized_keys
RUN chown user:consultores_ext /home/user/.ssh/authorized_keys && \
    chmod 600 /home/user/.ssh/authorized_keys && \
    chmod 750 /home/user
RUN ssh-keygen -A
EXPOSE 22

COPY ./docker/entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

