#
# ------------------------------------------------------------------------------
# Antes tenía agregado de servidor SSH desde sebastianf101/bsm-studio-paq:v2.2.1
# Refs: https://github.com/atmoz/sftp
#
# Define build-time arguments with default values
ARG BASE_IMAGE_REPO=bsm-studio-paq
ARG BASE_IMAGE_VERSION=latest
ARG REPO_SOURCE_URL

# Use the supplied base image name and version
# ghcr.io/sferro-besmart/my-rstudio:1.0.1
FROM ${BASE_IMAGE_REPO}:${BASE_IMAGE_VERSION} AS base

# Apply metadata labels dynamically
#LABEL org.opencontainers.image.source=${REPO_SOURCE_URL}

# Build context is project root.
COPY ./volume_versiones/ /var/data/besmart/versiones
COPY ./docker/RProfile.site /usr/local/lib/R/etc/Rprofile.site
RUN chown -R root:root /var/data/besmart/versiones
RUN chmod -R 755 /var/data/besmart/versiones
RUN mkdir -p /var/data/besmart/docker
RUN mkdir -p /home/user/Documents/besmart
# Util para parches
COPY ./docker/Init_users.sh /var/data/besmart/docker/
#
# Alta de usuarios
RUN addgroup --gid 1000 consultores_ext
COPY ./docker/users.conf.newusers /etc/security/users.conf.newusers
RUN chmod 0600 /etc/security/users.conf.newusers
RUN newusers /etc/security/users.conf.newusers
#
# Inicializa los directorios del usuario.
RUN chmod +x /var/data/besmart/docker/Init_users.sh
RUN /var/data/besmart/docker/Init_users.sh
# set up SSH
# Set up SSH for user 'user'# SSH config (pubkey only) with StrictModes
RUN mkdir -p /var/run/sshd && \
    sed -ri 's|^#?PasswordAuthentication.*|PasswordAuthentication no|' /etc/ssh/sshd_config && \
    sed -ri 's|^#?PermitRootLogin.*|PermitRootLogin no|' /etc/ssh/sshd_config && \
    sed -ri 's|^#?PubkeyAuthentication.*|PubkeyAuthentication yes|' /etc/ssh/sshd_config && \
    sed -ri 's|^#?AuthorizedKeysFile.*|AuthorizedKeysFile .ssh/authorized_keys|' /etc/ssh/sshd_config && \
    sed -ri 's|^#?StrictModes.*|StrictModes yes|' /etc/ssh/sshd_config && \
    echo 'PermitUserEnvironment yes' >> /etc/ssh/sshd_config

# ~/.ssh with strict perms for 'user'
RUN install -d -m 700 -o user -g consultores_ext /home/user/.ssh

# Add the public key as authorized_keys
COPY ./docker/id_rocker.pub /home/user/.ssh/authorized_keys
RUN chown user:consultores_ext /home/user/.ssh/authorized_keys && \
    chmod 600 /home/user/.ssh/authorized_keys && \
    chmod 750 /home/user
RUN ssh-keygen -A
EXPOSE 22

COPY ./docker/entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

