project:
  title: "SM"
#  post-render: /bin/bash ./Scripts/post-render.sh

date: today
date-format: long

author: "BeSmart"
lang: "es-ar"

format:
  html:
    keep_md: false
    toc: true
    toc_depth: 7
    toc_float: true
    toc_collapsed: true
    toc-location: left    
    smooth_scroll: true
    embed-resources: true
    self-contained-math: true
    html-math-method: katex
    echo: false
    mermaid:
      theme: neutral
    grid:
      sidebar-width: 250px
      body-width: 1200px
      margin-width: 50px

editor_options:
  chunk_output_type: inline
  markdown: 
    wrap: sentence
    

    


