#
# ------------------------------------------------------------------------------
# Antes tenía agregado de servidor SSH desde sebastianf101/bsm-studio-paq:v2.2.1 
# Refs: https://github.com/atmoz/sftp
#
# Define build-time arguments with default values
ARG BASE_IMAGE_REPO
ARG BASE_IMAGE_VERSION=latest
ARG REPO_SOURCE_URL

# Ensure arguments have valid values before using them
RUN if [ -z "$BASE_IMAGE_REPO" ] || [ -z "$BASE_IMAGE_VERSION" ]; then \
      echo "❌ ERROR: Missing BASE_IMAGE arguments!" >&2; exit 1; \
    else \
      echo "✅ Base Image Arguments Validated!"; \
      echo "🔹 BASE_IMAGE_REPO: $BASE_IMAGE_REPO"; \
      echo "🔹 BASE_IMAGE_VERSION: $BASE_IMAGE_VERSION"; \
    fi

# Use the supplied base image name and version
FROM ${BASE_IMAGE_REPO}:${BASE_IMAGE_VERSION} AS base

# Accept additional build-time arguments (must be defined again after FROM)
ARG REPO_SOURCE_URL

# Apply metadata labels dynamically
LABEL org.opencontainers.image.source=${REPO_SOURCE_URL}

# Chequeo que estoy en el directorio principal. Uno arriba de Instal.
COPY ./Instal/rstudio-prefs.json /etc/rstudio/rstudio-prefs.json
COPY ./Instal/FiraCode-Retina.ttf /etc/rstudio/fonts/
COPY ./volume_versiones/ /var/data/besmart/versiones
COPY ./Instal/RProfile.site /usr/local/lib/R/etc/Rprofile.site
RUN chown -R rstudio:rstudio /var/data/besmart/versiones
RUN chmod -R 755 /var/data/besmart/versiones
RUN mkdir -p /var/data/besmart/Instal
RUN mkdir -p /home/rstudio/Documents/besmart
# No es necesario tenerlo cómo volumen
# VOLUME /var/data/besmart/versiones
# Util para parches
COPY ./Instal/Init_users.sh /var/data/besmart/Instal/
#
# Alta de usuarios
RUN addgroup --gid 1100 admin 
RUN addgroup --gid 1200 consultores
RUN addgroup --gid 1300 consultores_ext 
RUN addgroup --gid 2000 compartido
COPY ./Instal/users.conf.newusers.local /etc/security/
RUN chmod 0600 //etc/security/users.conf.newusers.local
RUN newusers //etc/security/users.conf.newusers.local
#
# Mecanismos de autenticación.  Sin uso. Falta mejorar
# COPY ./Instal/login.defs /etc/login.defs
# Funcionó la autenticación por pam_userdb pero no resuelve el user provisioning.  
# Inicializa los directorios de cada usuario. 
RUN /var/data/besmart/Instal/Init_users.sh
