name: Docker Multi-Build

on:
  schedule:
    - cron: '43 15 * * *'
  push:
    branches: [ "main" ]
    tags: [ '*.*.*' ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_PAQ: bsm-studio-paq
  IMAGE_NAME_STUDIO: bsm-studio

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Cosign
        if: github.event_name != 'pull_request'      
        uses: sigstore/cosign-installer@v3.8.1
        with:
          cosign-release: 'v2.4.3'

      - name: Check install!
        run: cosign version

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata (STUDIO)
        id: meta_studio
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}

      - name: Build and push Docker image (PAQ)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Instal/Dockerfile.bsm-studio-paq
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.IMAGE_NAME_PAQ }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Docker image (STUDIO)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Instal/Dockerfile.bsm-studio
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta_studio.outputs.tags }}
          labels: ${{ steps.meta_studio.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Sign the published Docker image
        if: ${{ github.event_name != 'pull_request' }}
        env:
          TAGS_STUDIO: ${{ steps.meta_studio.outputs.tags }}
          DIGEST_STUDIO: ${{ steps.build-and-push.outputs.digest }}
        run: |
          echo "${TAGS_STUDIO}" | xargs -I {} cosign sign --yes {}@${DIGEST_STUDIO}
